# This workflow will install Python dependencies, run tests, lint and cov with a single version of Python

name: Running tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checking out repo 
      uses: actions/checkout@v3

    - name: Set up Python 
      uses: actions/setup-python@v3
      with:
        python-version: "3.13"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov pylint
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Setting Environment variables
      run: |
          echo "ENVIRONMENT=development" >> $GITHUB_ENV
          echo "LOG_LEVEL=DEBUG" >> $GITHUB_ENV
          echo "HISTORY_FILE=data/calculation_history.csv" >> $GITHUB_ENV

    - name: Creating logs directory
      run: |
        mkdir -p logs

    - name: Running tests with pytest
      run: |
        pytest

    - name: Running tests with pytest
      run: |
          pytest --pylint

    - name: Running tests with coverage
      run: |
        pytest --pylint --cov